### ISSUE TITLE
代码轮子回复列表

### ISSUE THREAD

**Issue by simcyber** [simcyber/simcyber.github.io#1]
如果侵犯了您的权益，请回复，本人将及时删除

**Comment by mashaofei** [comment]
可以给个nginx下的伪静态规则吗?

**Comment by simcyber** [comment]
Hello~这个是用ThinkPHP 3.2 写的，文档中的规则都试用
http://document.thinkphp.cn/manual_3_2.html#url_rewrite

试一下行不行？

> [ Nginx ]
> 在Nginx低版本中，是不支持PATHINFO的，但是可以通过在Nginx.conf中配置转发规则实现：
>   location / { // …..省略部分代码
>    if (!-e $request_filename) {
>    rewrite  ^(._)$  /index.php?s=$1  last;
>    break;
>     }
>  }
> 其实内部是转发到了ThinkPHP提供的兼容模式的URL，利用这种方式，可以解决其他不支持PATHINFO的WEB服务器环境。
> 如果你的ThinkPHP安装在二级目录，Nginx的伪静态方法设置如下，其中youdomain是所在的目录名称。
> location /youdomain/ {
>     if (!-e $request_filename){
>         rewrite  ^/youdomain/(._)$  /youdomain/index.php?s=$1  last;
>     }
> }
> 原来的访问URL：
> http://serverName/index.php/模块/控制器/操作/[参数名/参数值...]
> 设置后，我们可以采用下面的方式访问：
> http://serverName/模块/控制器/操作/[参数名/参数值...]
